INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SPECMONITOR specmonitor)

FIND_PATH(
    SPECMONITOR_INCLUDE_DIRS
    NAMES specmonitor/api.h
    HINTS $ENV{SPECMONITOR_DIR}/include
        ${PC_SPECMONITOR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SPECMONITOR_LIBRARIES
    NAMES gnuradio-specmonitor
    HINTS $ENV{SPECMONITOR_DIR}/lib
        ${PC_SPECMONITOR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPECMONITOR DEFAULT_MSG SPECMONITOR_LIBRARIES SPECMONITOR_INCLUDE_DIRS)
MARK_AS_ADVANCED(SPECMONITOR_LIBRARIES SPECMONITOR_INCLUDE_DIRS)

